apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-namespace-map
  namespace: kube-system
data:
  namespace_stream_map.txt: |
    happyapp-prod=789
    happyapp-scheduler=456
    happyapp-stage=123