apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-namespace-map
  namespace: kube-system
data:
  namespace_stream_map.txt: |
    happyapp-prod=6926b411cbd41d6f3541da9d
    happyapp-scheduler=6926b444cbd41d6f3541db33
    happyapp-stage=6926b455cbd41d6f3541db73