apiVersion: v1
kind: Service
metadata:
  name: graylog-gelf-docker-input
  namespace: graylog
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: graylog
  ports:
    - protocol: TCP
      port: 12202      # GELF TCP port inside Graylog
      targetPort: 12202
      nodePort: 31221  # NodePort you expose externally