apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: kube-system
  labels:
    k8s-app: fluent-bit
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit
  template:
    metadata:
      labels:
        k8s-app: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      tolerations:
      - operator: Exists
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:3.2.10
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: config
          mountPath: /fluent-bit/etc/
        - name: fluentbit-storage
          mountPath: /var/fluent-bit/storage
        - name: lua-scripts
          mountPath: /fluent-bit/scripts/
        - name: docker-logs
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentbit-storage
          mountPath: /var/fluent-bit/storage
        - name: fluentbit-state
          mountPath: /var/fluent-bit/state
      #  - name: tls
      #    mountPath: /fluent-bit/tls
      #    readOnly: true

      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: config
        configMap:
          name: fluent-bit-config
      - name: fluentbit-storage
        hostPath:
          path: /var/lib/fluent-bit
          type: DirectoryOrCreate
      - name: lua-scripts
        configMap:
          name: fluent-bit-lua-scripts
          items:
            - key: combine_fields.lua
              path: combine_fields.lua
      - name: docker-logs
        hostPath:
          path: /var/lib/docker/containers
          type: Directory
      - name: fluentbit-storage
        hostPath:
          path: /var/lib/fluent-bit
          type: DirectoryOrCreate
      - name: fluentbit-state
        hostPath:
          path: /var/lib/fluent-bit/state
          type: DirectoryOrCreate
      #- name: tls
      #  secret:
      #    secretName: fluent-bit-tls # optional (create if TLS needed)